### ISSUE TITLE
Statistics not generatet in STAC collection

### ISSUE THREAD

**Issue by SwordSaintLancelot** [US-GHG-Center/ghgc-data-airflow#20]
The stac collection with collection id `oco2geos-co2-daygrid-v10r` does not show any statistics like, histogram values, minimum and maximum values for the assets.

![image](https://github.com/US-GHG-Center/ghgc-docs/assets/34275219/8637928b-12ea-490d-81f4-9edad6b40629)

## Acceptance criteria

- [ ] Update the STAC collection

**Comment by slesaad** [comment]
Working here: https://github.com/US-GHG-Center/ghgc-data-airflow/pull/19

**Comment by slesaad** [comment]
Deployed to production, now re-running ingests for the three collections. Status for each collection in the comment ⬆️
